### PR TITLE
{Feature} Added devignetting demo 

### PR DESCRIPTION
**Pull request by nathanjzhao**
Addresses #99 and provides example of how to apply inverse vignette image to image in original .ipynb notebook.

### CODE REVIEW

**Comment by chpeng-fb** [comment]
Hi Nathan,

Thank you for creating the pull request. We are currently working on the pull request process. 

In the mean time, vignetting mask is currently a general mask that is not calibrated per camera. So providing the capability as a tutorial could be misleading without understanding the risks. 

Whats you thoughts on this? Does the devignetting work for your process without a problem?

Thanks
Cheng

**Comment by nathanjzhao** [comment]
Hi Cheng,

The devignetting works fully for my glasses without a problem, and the mask I utilized was based on the vignetting mask provided in #99. There could be further additions to the tutorial for accounting for various camera vignetting, but otherwise, at the moment, the current code works for my glasses.

Thanks,
Nathan

**Comment by AntonioMacaronio** [comment]
Is there a way to turn vignetting off when recording? I just spent a large amount of time filming data and I have come to believe I have fallen victim to the vignetting masks in my data, which has severely impacted my 3d reconstructions with gaussian splatting / neural radiance fields

**Comment by nathanjzhao** [comment]
Unfortunately, vignetting is naturally a result of the fisheye lens. This is why I wanted to create a demo for devignetting images/video frames. Feel free to look at my PR for a template for how to devignette the videos!

**Comment by nathanjzhao** [comment]
Hey, just wondering about the status of this PR -- Let me know if any edits are needed.

**Comment by thucz** [comment]
> Addresses #99 and provides example of how to apply inverse vignette image to image in original .ipynb notebook.

Hi! where did you put the devignetting demo?

**Pull request closed without merging**
